DROP TABLE IF EXISTS comments, posts;

CREATE TABLE IF NOT EXISTS posts(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(256) NOT NULL,
    image_path VARCHAR(512),
    text VARCHAR NOT NULL,
    likes_count BIGINT,
    tags VARCHAR[]
);

CREATE TABLE IF NOT EXISTS comments(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    text VARCHAR(256) NOT NULL,
    FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE
);